[merge]
    command = "emacs"
    args = ["-nw", "-ediff-merge", "{{ .Source }}", "{{ .Destination }}", "{{ .Target }}"]

[diff]
    command = "emacs"
    args = ["-nw", "-ediff", "{{ .Destination }}", "{{ .Target }}"]
