[merge]
    command = "emacs"
    args = ["-nw", "-ediff-merge", "{{ .Source }}", "{{ .Destination }}", "{{ .Target }}"]

[diff]
    command = "emacs"
    args = ["-nw", "-ediff", "{{ .Destination }}", "{{ .Target }}"]

[edit]
    command = "emacs"
    args = ["-nw"]

[data.terminal]
    font = "hack"
    fontsize = "12"
